project:
  type: website

website:
  title: "Benjamín Adasme Jara"
  favicon: "images/foto Benjamín Adasme.jpg"
  navbar:
    left: 
      - href: index.qmd
        text: Inicio
      - href: cv.qmd
        text: CV
      - href: projects.qmd
        text: Proyectos
      - href: tidytuesday.qmd
        text: Tidy Tuesday
    right:
      - about.qmd
      - icon: github
        href: https://github.com/benjamin-adasme
      - icon: twitter
        href: https://twitter.com/AdasmeBenja
  page-footer: 
    center: |
      Benjamín Adasme Jara - 2025
    left: |
      Hecho con [Quarto](https://quarto.org/)
    right: |
      [Github Repo](https://github.com/benjamin-adasme)
    #background: "#2780e3"
format:
  html:
    theme: 
      light: flatly
      dark: [darkly, theme-dark.scss]
    css: styles.css

editor: source

